# Generated by Django 5.2.6 on 2025-10-23 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_old_category_alter_todo_priority_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='old_category',
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3, help_text='1=High, 2=Medium, 3=Low', validators=[django.core.validators.MinValueValidator(1, message='Priority must be at least 1'), django.core.validators.MaxValueValidator(3, message='Priority cannot be higher than 3')]),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
